# -*- coding: utf-8 -*-
"""filter_signals.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-fRhRdS1jNmqoxqU1zir_lv-DWpCEIw
"""

from scipy.signal import butter, filtfilt

def bandpass_filter(data, fs, low=0.17, high=0.4, order=4):
    nyquist = 0.5 * fs
    lowcut = low / nyquist
    highcut = high / nyquist
    b, a = butter(order, [lowcut, highcut], btype='band')
    return filtfilt(b, a, data)