# -*- coding: utf-8 -*-
"""cnn_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovSkCbZCbRkVIzn58mjT4zF8l2RfU9gs
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout

def build_cnn(input_shape, num_classes):
    """
    Build a 1D Convolutional Neural Network for time-series classification.

    Args:
        input_shape (tuple): Shape of input data (timesteps, 1).
        num_classes (int): Number of output classes.

    Returns:
        model (tf.keras.Model): Compiled CNN model.
    """
    model = Sequential([
        Conv1D(filters=32, kernel_size=5, activation='relu', input_shape=input_shape),
        MaxPooling1D(po