# -*- coding: utf-8 -*-
"""conv_lstm_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovSkCbZCbRkVIzn58mjT4zF8l2RfU9gs
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, TimeDistributed, Flatten, Reshape

def build_conv_lstm(input_shape, num_classes):
    model = Sequential()
    model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=input_shape))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Reshape((input_shape[0]//2, 32)))  # match LSTM input: (timesteps, features)
    model.add(LSTM(64))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

